## About this app

This software was developed for the project Lyoluminescence, to access the PMT

**Version**: 0.1.0 [2022-03-23] ALPHA VERSION

**Author**: Sebastian Kreutzer, Institute of Geography, Ruprecht-Karl University of Heidelberg, Germany

**Contact**: sebastian.kreutzer@uni-heidelberg.de

**Bug reporting**: ... nothing yet ... 
  
## How to cite?

... nothing yet ... 

## Licence

This program is free software: you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU [General Public License](https://www.gnu.org/licenses/gpl-3.0.en.html) for more details

## Instructions and limitations

* The channel time is limited to settings of 10 to 99 (0.01 to 0.99 s)
* Pressing the button invokes a delay, this is required by the connection and 
not a bug
